name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "project/water_potability_preprocessing.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.11"
      
      # Check Env
      - name: Check Env
        run: |
          echo $CSV_URL
      
      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow numpy pandas scikit-learn

      # Run as a mlflow project
      - name: Run mlflow project
        run: |
          mlflow run project \
            --entry_point modelling \
            --env-manager=local \
            -p n_estimators=100 \
            -p max_depth=5 \
            -p dataset=${{ env.CSV_URL }}

      # Save models to Github Repository
      - name: Save mlruns to Repository
        run: |
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}
          git add mlruns/
          git commit -m "Save mlruns from CI run"
          git push origin main